(() => {
'use strict';
const episodes = window.EPISODES || [];
const audio = document.getElementById('audio');
const homeView = document.getElementById('homeView');
const listView = document.getElementById('listView');
const episodeList = document.getElementById('episodeList');
const playerHome = document.getElementById('playerHome');
const playerList = document.getElementById('playerList');
const networkBadge = document.getElementById('networkBadge');
const STORAGE_KEY='tf_pwa_state_v1';
const AUDIO_CACHE='tf-audio-v1';
let state={lastId:null,positions:{},speed:1,durations:{}};
try{state={...state,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch(e){}
state.durations=state.durations||{};
episodes.forEach(ep=>{const d=Number(state.durations[ep.id]);if(Number.isFinite(d)&&d>0){ep.duration=d;if(ep.parts.length===1)ep.parts[0].duration=d}});
let current=null, partIndex=0, loadingSeek=null, lastPersist=0, activeCategory='A';
const icons={play:'<svg viewBox="0 0 32 32"><path d="M10 6.8c0-1.35 1.48-2.18 2.64-1.48l13.1 8.08a3.04 3.04 0 0 1 0 5.2l-13.1 8.08A1.73 1.73 0 0 1 10 25.2V6.8z"/></svg>',pause:'<svg viewBox="0 0 32 32"><path d="M8 6h6v20H8zM18 6h6v20h-6z"/></svg>',prev:'<svg viewBox="0 0 32 32"><path d="M7 7h3v18H7zm4 9 14-9v18z"/></svg>',next:'<svg viewBox="0 0 32 32"><path d="M22 7h3v18h-3zm-15 0 14 9-14 9z"/></svg>'};
const categoryMeta={
  A:{eyebrow:'A · GRUNDLAGEN',title:'Zauberpodcast',subtitle:'Grundlagen & Zauberzettel',className:''},
  B:{eyebrow:'B · LETZTE PRÜFUNG',title:'Prüfungspodcast',subtitle:'Letzte Prüfung / Prüfungsschwerpunkte',className:'violet'},
  C:{eyebrow:'C · STILKUNDE',title:'Stilkunde',subtitle:'Architektur · Epochen · Gestaltung',className:'gold'}
};
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function fmt(sec){if(!Number.isFinite(sec))return '0:00';sec=Math.max(0,Math.round(sec));const m=Math.floor(sec/60),s=sec%60;return `${m}:${String(s).padStart(2,'0')}`}
function position(id){return Number(state.positions?.[id]||0)}
function percent(ep){return Math.max(0,Math.min(100,(position(ep.id)/ep.duration)*100||0))}
function currentGlobalTime(){return current ? (current.parts[partIndex]?.start||0)+(audio.currentTime||0) : 0}
function partForTime(ep,t){let idx=ep.parts.length-1;for(let i=0;i<ep.parts.length;i++){const p=ep.parts[i];if(t < p.start+p.duration-.02){idx=i;break}}return idx}
function visualClass(cat){return categoryMeta[cat]?.className||''}
function setMediaSession(){if(!current||!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:`${current.code} – ${current.title}`,artist:current.categoryName,album:'TheorieFachteil',artwork:[{src:'./icons/icon-192.png',sizes:'192x192',type:'image/png'},{src:'./icons/icon-512.png',sizes:'512x512',type:'image/png'}]});navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('seekbackward',()=>seekBy(-15));navigator.mediaSession.setActionHandler('seekforward',()=>seekBy(15));navigator.mediaSession.setActionHandler('previoustrack',()=>changeEpisode(-1));navigator.mediaSession.setActionHandler('nexttrack',()=>changeEpisode(1))}catch(e){}}
function loadPart(idx,localTime=0,autoplay=false){if(!current)return;partIndex=Math.max(0,Math.min(current.parts.length-1,idx));loadingSeek=Math.max(0,localTime);audio.src=current.parts[partIndex].file;audio.playbackRate=state.speed||1;audio.load();const start=()=>{if(loadingSeek!==null){try{audio.currentTime=Math.min(loadingSeek,Math.max(0,(audio.duration||99999)-.05))}catch(e){}loadingSeek=null}if(autoplay)audio.play().catch(()=>{});audio.removeEventListener('loadedmetadata',start)};audio.addEventListener('loadedmetadata',start)}
function selectEpisode(id,autoplay=true){const ep=episodes.find(e=>e.id===Number(id));if(!ep)return;current=ep;state.lastId=ep.id;activeCategory=ep.category;saveState();const t=Math.min(position(ep.id),Math.max(0,ep.duration-.2));const idx=partForTime(ep,t);loadPart(idx,t-ep.parts[idx].start,autoplay);setMediaSession();renderAll()}
function seekTo(globalTime){if(!current)return;const t=Math.max(0,Math.min(current.duration-.05,globalTime));state.positions[current.id]=t;saveState();const idx=partForTime(current,t);if(idx===partIndex){audio.currentTime=t-current.parts[idx].start}else{loadPart(idx,t-current.parts[idx].start,!audio.paused)}renderPlayers()}
function seekBy(delta){seekTo(currentGlobalTime()+delta)}
function categoryEpisodes(cat){return episodes.filter(e=>e.category===cat)}
function changeEpisode(dir){if(!current)return;const list=categoryEpisodes(current.category);const i=list.findIndex(e=>e.id===current.id);const n=i+dir;if(n>=0&&n<list.length)selectEpisode(list[n].id,true)}
function playerMarkup(compact=false){const ep=current || episodes.find(e=>e.id===Number(state.lastId));const disabled=!ep;const playing=current && !audio.paused;const t=current?currentGlobalTime():(ep?position(ep.id):0);const pct=ep?Math.max(0,Math.min(100,(t/ep.duration)*100)):0;const cls=ep?visualClass(ep.category):'';return `<div class="player-title"><span class="history-icon">↶</span><h2>Zuletzt gehört</h2></div>${ep?`<div class="now-card"><div class="ep-tile ${cls}">${String(ep.id).padStart(2,'0')}</div><div class="now-copy"><span class="category-chip ${cls}">${ep.categoryName}</span><h3>${ep.code} – ${ep.title}</h3></div></div>`:`<div class="empty-copy"><h3>Noch nichts gehört</h3><p>Wähle oben einen Podcast und starte eine Episode.</p></div>`}<div class="progress-block"><div class="progress-row"><span>Fortschritt</span><span>${fmt(t)}${ep?' / '+fmt(ep.duration):''}</span></div><div class="progress" data-seekbar><div style="width:${pct}%"></div></div></div><div class="controls"><button class="control" data-action="prev" ${disabled?'disabled':''}>${icons.prev}</button><button class="control seek" data-action="back" ${disabled?'disabled':''}>−15</button><button class="play-main" data-action="play" ${disabled?'disabled':''}>${playing?icons.pause:icons.play}</button><button class="control seek" data-action="forward" ${disabled?'disabled':''}>+15</button><button class="control" data-action="next" ${disabled?'disabled':''}>${icons.next}</button></div><div class="speed-row"><span>GESCHWINDIGKEIT</span><div class="speeds">${[1,1.5,2].map(s=>`<button class="speed ${Number(state.speed)===s?'active':''}" data-speed="${s}">${String(s).replace('.',',')}×</button>`).join('')}</div></div><div class="player-foot">Fortschritt wird lokal auf diesem Gerät gespeichert.</div>`}
function bindPlayer(root){root.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='play'){if(!current&&state.lastId)selectEpisode(state.lastId,true);else if(audio.paused)audio.play().catch(()=>{});else audio.pause()}if(a==='back')seekBy(-15);if(a==='forward')seekBy(15);if(a==='prev')changeEpisode(-1);if(a==='next')changeEpisode(1)}));root.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{state.speed=Number(b.dataset.speed);audio.playbackRate=state.speed;saveState();renderPlayers()}));const bar=root.querySelector('[data-seekbar]');if(bar&&current){bar.style.cursor='pointer';bar.addEventListener('click',e=>{const r=bar.getBoundingClientRect();seekTo(((e.clientX-r.left)/r.width)*current.duration)})}}
function renderPlayers(){playerHome.innerHTML=playerMarkup(false);playerList.innerHTML=playerMarkup(true);bindPlayer(playerHome);bindPlayer(playerList)}
function renderList(cat){activeCategory=cat;const meta=categoryMeta[cat]||categoryMeta.A;document.getElementById('listEyebrow').textContent=meta.eyebrow;document.getElementById('listTitle').textContent=meta.title;document.getElementById('listSubtitle').textContent=meta.subtitle;episodeList.innerHTML=categoryEpisodes(cat).map(ep=>`<button class="episode-row ${meta.className}" data-episode="${ep.id}"><span class="episode-number">${String(ep.id).padStart(2,'0')}</span><span class="episode-copy"><strong>${ep.code} · ${ep.title}</strong><span class="episode-meta"><span>${fmt(ep.duration)}</span><span class="mini-progress"><span style="width:${percent(ep)}%"></span></span><span>${Math.round(percent(ep))}%</span></span></span><span class="chev">›</span></button>`).join('');episodeList.querySelectorAll('[data-episode]').forEach(b=>b.addEventListener('click',()=>selectEpisode(b.dataset.episode,true)))}
function renderAll(){renderPlayers();if(!listView.classList.contains('hidden'))renderList(activeCategory)}
function showList(cat){homeView.classList.add('hidden');listView.classList.remove('hidden');renderList(cat);renderPlayers();window.scrollTo({top:0,behavior:'smooth'})}
function showHome(){listView.classList.add('hidden');homeView.classList.remove('hidden');renderPlayers();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>showList(b.dataset.category)));document.getElementById('backHome').addEventListener('click',showHome);
audio.addEventListener('loadedmetadata',()=>{if(!current||current.parts.length!==1||!Number.isFinite(audio.duration)||audio.duration<=0)return;const d=audio.duration;current.duration=d;current.parts[0].duration=d;state.durations[current.id]=d;saveState();renderAll()});
audio.addEventListener('play',()=>{if('mediaSession'in navigator)try{navigator.mediaSession.playbackState='playing'}catch(e){}renderPlayers()});audio.addEventListener('pause',()=>{if('mediaSession'in navigator)try{navigator.mediaSession.playbackState='paused'}catch(e){}renderPlayers()});audio.addEventListener('timeupdate',()=>{if(!current)return;const t=currentGlobalTime();state.positions[current.id]=t;const now=Date.now();if(now-lastPersist>1500){saveState();lastPersist=now}renderPlayers();if(!listView.classList.contains('hidden'))renderList(activeCategory)});audio.addEventListener('ended',()=>{if(!current)return;if(partIndex<current.parts.length-1){loadPart(partIndex+1,0,true)}else{state.positions[current.id]=current.duration;saveState();renderAll()}});audio.addEventListener('ratechange',()=>{if(audio.playbackRate!==state.speed)audio.playbackRate=state.speed});window.addEventListener('pagehide',saveState);
function updateNetwork(){const online=navigator.onLine;networkBadge.classList.toggle('offline',!online);networkBadge.querySelector('span:last-child').textContent=online?'ONLINE':'OFFLINE'}window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();
// Offline manager – bleibt zunächst kompatibel mit der bisherigen Oberfläche.
const modal=document.getElementById('offlineModal');function openOffline(){modal.classList.remove('hidden');refreshOfflineStatus()}function closeOffline(){modal.classList.add('hidden')}document.getElementById('offlineButton').addEventListener('click',openOffline);networkBadge.addEventListener('click',openOffline);document.getElementById('closeOffline').addEventListener('click',closeOffline);modal.addEventListener('click',e=>{if(e.target===modal)closeOffline()});
async function cachedCount(){if(!('caches'in window))return {count:0,total:0};const c=await caches.open(AUDIO_CACHE);const keys=await c.keys();const wanted=new Set(episodes.flatMap(e=>e.parts.map(p=>new URL(p.file,location.href).href)));const audioKeys=keys.filter(k=>wanted.has(k.url));return {count:audioKeys.length,total:wanted.size}}
async function refreshOfflineStatus(){const s=document.getElementById('offlineStatus');try{const c=await cachedCount();s.textContent=`${c.count} von ${c.total} Audiodateien lokal vorgemerkt.`}catch(e){s.textContent='Offline-Speicher ist in diesem Browser nicht verfügbar.'}}
async function downloadCategory(cat){if(!('caches'in window)){alert('Cache Storage wird hier nicht unterstützt.');return}const eps=cat==='ALL'?episodes:episodes.filter(e=>e.category===cat);const files=eps.flatMap(e=>e.parts.map(p=>p.file));const cache=await caches.open(AUDIO_CACHE);const wrap=document.getElementById('downloadProgressWrap'),bar=document.getElementById('downloadBar'),txt=document.getElementById('downloadText'),pct=document.getElementById('downloadPct');wrap.classList.remove('hidden');let done=0;for(const file of files){txt.textContent=`Speichere ${done+1} / ${files.length}`;try{const req=new Request(file,{cache:'no-store'});const existing=await cache.match(req);if(!existing){const res=await fetch(req);if(!res.ok)throw new Error(String(res.status));await cache.put(req,res.clone())}}catch(e){txt.textContent=`Fehler bei ${file}`;throw e}done++;const p=Math.round(done/files.length*100);bar.style.width=p+'%';pct.textContent=p+'%'}txt.textContent='Offline-Speicherung abgeschlossen.';await refreshOfflineStatus()}
document.querySelectorAll('[data-offline-cat]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await downloadCategory(b.dataset.offlineCat)}catch(e){alert('Download wurde unterbrochen. Bitte erneut versuchen. Bereits gespeicherte Dateien bleiben erhalten.')}finally{b.disabled=false}}));document.getElementById('clearOffline').addEventListener('click',async()=>{if(confirm('Alle lokal gespeicherten Podcast-Audios löschen?')){await caches.delete(AUDIO_CACHE);document.getElementById('downloadBar').style.width='0%';document.getElementById('downloadPct').textContent='0%';await refreshOfflineStatus()}});
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
if(state.lastId){current=episodes.find(e=>e.id===Number(state.lastId))||null;if(current){activeCategory=current.category;const t=Math.min(position(current.id),Math.max(0,current.duration-.2));partIndex=partForTime(current,t);loadPart(partIndex,t-current.parts[partIndex].start,false);setMediaSession()}}
renderAll();
})();
