window.EPISODES = [
  {"id":1,"code":"EP1","category":"A","categoryName":"Zauberpodcast","title":"Chemie & Bauphysik","duration":1985.654,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP1.Chemie_und_Bauphysik_fur_die_Malermeisterprufung.m4a","duration":1985.654,"start":0.0}]},
  {"id":2,"code":"EP2","category":"A","categoryName":"Zauberpodcast","title":"Das chemische Kraftwerk im Farbeimer","duration":1766.133,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP2.Das_chemische_Kraftwerk_im_Farbeimer.m4a","duration":1766.133,"start":0.0}]},
  {"id":3,"code":"EP3","category":"A","categoryName":"Zauberpodcast","title":"Kalkkreislauf, Rissdiagnostik & Betonsanierung","duration":1495.528,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP3.Kalkkreislauf_Rissdiagnostik_und_fachgerechte_Betonsanierung.m4a","duration":1495.528,"start":0.0}]},
  {"id":4,"code":"EP4","category":"A","categoryName":"Zauberpodcast","title":"Molekularer Krieg gegen Rost & Feuer","duration":1678.292,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP4.Molekularer_Krieg_gegen_Rost_und_Feuer.m4a","duration":1678.292,"start":0.0}]},
  {"id":5,"code":"EP5","category":"A","categoryName":"Zauberpodcast","title":"Gitterschnitt, Spritztechnik & Wandbekleidung","duration":1641.929,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP5.Gitterschnitt_Spritztechnik_und_Wandbekleidung_fur_Malermeister.m4a","duration":1641.929,"start":0.0}]},
  {"id":6,"code":"EP6","category":"A","categoryName":"Zauberpodcast","title":"WDVS, Brandschutz & Bauphysik","duration":892.854,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP6.WDVS_Brandschutz_und_Bauphysik_zur_Meisterprufung.m4a","duration":892.854,"start":0.0}]},
  {"id":7,"code":"EP7","category":"A","categoryName":"Zauberpodcast","title":"Bauphysik & Architekturgeschichte","duration":1237.136,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP7.Bauphysik_und_Architekturgeschichte_fur_die_Malermeisterprufung.m4a","duration":1237.136,"start":0.0}]},
  {"id":8,"code":"EP8","category":"B","categoryName":"Prüfungspodcast","title":"Vom brennenden Lappen zum Kalkkreislauf","duration":1612.974,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP08.Vom_brennenden_Lappen_zum_Kalkkreislauf.m4a","duration":1612.974,"start":0.0}]},
  {"id":9,"code":"EP9","category":"B","categoryName":"Prüfungspodcast","title":"Bauphysik bei Holzfassaden & Innendämmungen","duration":1778.532,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP09.Bauphysik_bei_Holzfassaden_und_Innendammungen.m4a","duration":1778.532,"start":0.0}]},
  {"id":10,"code":"EP10","category":"B","categoryName":"Prüfungspodcast","title":"Zinkseife, Q3-Fallen & historische Fassaden","duration":1423.894,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP10.Zinkseife_Q3-Fallen_und_historische_Fassaden.m4a","duration":1423.894,"start":0.0}]},
  {"id":11,"code":"EP11","category":"B","categoryName":"Prüfungspodcast","title":"Trockeneisstrahlen, Vliestapeten & VOB","duration":1622.541,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP11.Trockeneisstrahlen_Vliestapeten_und_VOB_in_der_Meisterprufung.m4a","duration":1622.541,"start":0.0}]},
  {"id":12,"code":"EP12","category":"B","categoryName":"Prüfungspodcast","title":"Baustellenorganisation & Mitarbeiterführung","duration":1396.982,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP12.Baustellenorganisation_und_Mitarbeiterfuhrung_fur_Malermeister.m4a","duration":1396.982,"start":0.0}]},
  {"id":13,"code":"EP13","category":"B","categoryName":"Prüfungspodcast","title":"Warum Masken gegen Bleiweiß nicht ausreichen","duration":1359.668,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP13.Warum_Masken_gegen_Bleiweiss_nicht_ausreichen.m4a","duration":1359.668,"start":0.0}]},
  {"id":14,"code":"EP14","category":"B","categoryName":"Prüfungspodcast","title":"Bodenbeläge, Akustik & Denkmalschutz","duration":1898.185,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP14.Bodenbelage._Akustik_und_Denkmalschutz_fur_Malermeister.m4a","duration":1898.185,"start":0.0}]},
  {"id":15,"code":"EP15","category":"C","categoryName":"Stilkunde","title":"Von ägyptischer Ewigkeit zu romanischen Rundbögen","duration":1707.423,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP15.Von_agyptischer_Ewigkeit_zu_romanischen_Rundbogen.m4a","duration":1707.423,"start":0.0}]},
  {"id":16,"code":"EP16","category":"C","categoryName":"Stilkunde","title":"Gotik bis Rokoko und der Goldene Schnitt","duration":1498.115,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP16.Gotik_bis_Rokoko_und_der_Goldene_Schnitt.m4a","duration":1498.115,"start":0.0}]},
  {"id":17,"code":"EP17","category":"C","categoryName":"Stilkunde","title":"Von Klassizismus bis Bauhaus für Malermeister","duration":937.679,"parts":[{"file":"https://github.com/ollmann2410-ui/fachteilaudio/releases/download/audio-v1/EP17.Von_Klassizismus_bis_Bauhaus_fur_Malermeister.m4a","duration":937.679,"start":0.0}]}
];
